force-app/main/default/objects/Negoptim__Assortment_BU__c/Negoptim__Assortment_BU__c.object-meta.xml
<CustomObject>
    <label>Assortment BU</label>
    <nameField>
        <label>Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assortment BU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__BU_source__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_source__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>For ex.
Budget = Corporate BU country  /
Target = Managing channel  = HMSM + DRIVE, PROXI, WEB , CASH &amp; CARRY.  /  

Saisir &apos;..&apos; pour accéder à l&apos;ensemble des BU possibles pour le type de DV choisi.</inlineHelpText>
    <label>BU Source</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5) OR (6 AND 7))</booleanFilter>
        <errorMessage>BU_source__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__IsMasterBU__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Budget_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Target_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conso Target, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Nego_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Conso Target, Budget, Target</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_BU__c</referenceTo>
    <relationshipName>Assortment_BU</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__BU_Target__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_Target__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Budget = HMSM + DRIVE, PROXI, WEB, CASH &amp; CARRY.  /  
target/ Nego =Banner(ex. Carrefour HM, Carrefour SM, Intermarché.fr).  /  

Saisir &apos;..&apos; pour accéder à l&apos;ensemble des BU possibles pour le type choisi.</inlineHelpText>
    <label>BU Target</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2 AND 3) OR (4 AND 5) OR (6 AND 7))</booleanFilter>
        <errorMessage>BU_Target__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Budget_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__IsMasterBU__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conso Target, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Target_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Conso Target, Budget, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Nego_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_BU__c</referenceTo>
    <relationshipName>Assortment_BU1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Orga_HE__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Orga_HE__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product hierarchy</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Orga_HE__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_HE__c.Negoptim__Set_Assortment_Cluster_level__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_HE__c</referenceTo>
    <relationshipName>Assortment_BU</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Year__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Year__c</fullName>
    <description>Campaign year</description>
    <inlineHelpText>Campaign year</inlineHelpText>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/Negoptim__Orga_BU__c.object-meta.xml
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>BU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Country_origin__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Country_origin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TO BE DEFINED - Country of the Business Unit (List / Store / DC / Web)</description>
    <inlineHelpText>Entité Parente pour les Strates ou Pays de la BU</inlineHelpText>
    <label>Country Origin</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <errorMessage>Country_origin__c -Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_BU__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Banner</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Assortment Cluster, Store, Warehouse, Web, Assortment Cluster List</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_BU__c</referenceTo>
    <relationshipLabel>Business Units (Country origin)</relationshipLabel>
    <relationshipName>Business_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_HE__c/Negoptim__Orga_HE__c.object-meta.xml
<CustomObject>
    <description>Hierarchy of products (segmentation) needed for assortment management</description>
    <label>Hierarchy Element</label>
    <nameField>
        <label>Hierarchy Element</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarchy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ExecuteBatchInvocableExt.cls
/**
 * @author ULiT
 * @date 19/03/2024
 * @description executes batches, used in screen flows
*/
global class ExecuteBatchInvocableExt {
        
    @InvocableMethod(label = 'ExecuteBatch')
    global static void execute(List<BatchParametersWrapper> batchParamsList) {
        if (batchParamsList != null && !batchParamsList.isEmpty()) {
            BatchParametersWrapper batchParams = batchParamsList[0];
            switch on batchParams.batchName {
                when 'ConsolidateAssortmentBatchExt' {
                    List<Negoptim__Assortment_BU__c> assortments = [SELECT Id, Negoptim__BU_Source__c, Negoptim__Orga_HE__c, Negoptim__Year__c,
                                                                    Negoptim__BU_Target__r.Negoptim__Country_origin__c
                                                                    FROM Negoptim__Assortment_BU__c
                                                                    WHERE Id = :batchParams.recordId];
                    if (!assortments.isEmpty()) {
                        Negoptim.NegoptimBatch.executeBatch(new ConsolidateAssortmentBatchExt(ExecuteBatchInvocableExt.class.getName() + ' [' + batchParams.startedFrom + ']',
                                                                                              new Set<Id>{assortments[0].Negoptim__BU_Target__r.Negoptim__Country_origin__c},
                                                                                              new Set<Id>{assortments[0].Negoptim__BU_Source__c},
                                                                                              new Set<Id>{assortments[0].Negoptim__Orga_HE__c},
                                                                                              NULL,
                                                                                              new Set<Integer>{Integer.valueOf(assortments[0].Negoptim__Year__c)}), 200);
                    }
                }
            }
        }
    }
    
    global class BatchParametersWrapper {
        
        @InvocableVariable(required=true)
        global String batchName;
        @InvocableVariable
        global String startedFrom;
        @InvocableVariable
        global Id recordId;
    }
}