force-app/main/default/objects/Negoptim__Assortment_BU__c/Negoptim__Assortment_BU__c.object-meta.xml
<CustomObject>
    <label>Assortment BU</label>
    <nameField>
        <label>Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assortment BU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Orga_HE__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Orga_HE__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product hierarchy</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Orga_HE__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_HE__c.Negoptim__Set_Assortment_Cluster_level__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_HE__c</referenceTo>
    <relationshipName>Assortment_BU</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Negoptim__Assortment_type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open (in bulding process)</fullName>
                <default>true</default>
                <label>Open (in bulding process)</label>
            </value>
            <value>
                <fullName>Request for Approval</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Signed IN</fullName>
            </value>
            <value>
                <fullName>Signed OUT</fullName>
            </value>
            <value>
                <fullName>Closed (Upgraded version)</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/Negoptim__Assortment_Detail__c.object-meta.xml
<CustomObject>
    <description>Assortment product detail by BU</description>
    <label>Assortment Detail</label>
    <nameField>
        <displayFormat>ASD-{0}</displayFormat>
        <label>Assortiment Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assortment Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Assortment_BU__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Assortment_BU__c</fullName>
    <label>Assortment BU</label>
    <referenceTo>Negoptim__Assortment_BU__c</referenceTo>
    <relationshipLabel>Assortment BU Details</relationshipLabel>
    <relationshipName>Assortment_BU_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Brand__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Brand__c</fullName>
    <formula>Negoptim__Product__r.Negoptim__Brand__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Category__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Negoptim__Orga_HE__c.Negoptim__Level__c</field>
            <operation>equals</operation>
            <value>3,4</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_HE__c</referenceTo>
    <relationshipLabel>Assortment BU Details</relationshipLabel>
    <relationshipName>Assortment_BU_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>In preparation</label>
            </value>
            <value>
                <fullName>Request for Approval</fullName>
                <color>#78C953</color>
                <label>Request for Approval</label>
            </value>
            <value>
                <fullName>Validated</fullName>
                <color>#E27001</color>
                <label>Validated</label>
            </value>
            <value>
                <fullName>Previously Validated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Brand__c/Negoptim__Brand__c.object-meta.xml
<CustomObject>
    <description>Define the main information of the Brand</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Brand__c/fields/Negoptim__Brand_Parent__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Brand_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Parent</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Brand_Parent__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Brand__c.Negoptim__Brand_Parent__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Choose a master brand without Parent</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Brand__c</referenceTo>
    <relationshipLabel>Child Brands</relationshipLabel>
    <relationshipName>BrandChild</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Brand__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/Negoptim__Orga_BU__c.object-meta.xml
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>BU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Category__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Negoptim__Orga_HE__c.Negoptim__Set_Assortment_Cluster_level__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_HE__c</referenceTo>
    <relationshipLabel>Business Units</relationshipLabel>
    <relationshipName>Business_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__IsMasterBU__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__IsMasterBU__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to distinguished if the record is the master Org BU.</description>
    <inlineHelpText>Est-ce une BU (Enseigne, circuit...) sélectionnable pour l&apos;assortiment.</inlineHelpText>
    <label>Is Master BU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Layer_Nego_Conso__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Layer_Nego_Conso__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define the business unit can be used as aggregated level in the nego, assortment, contract, ...</description>
    <inlineHelpText>Cette BU est utilisée pr la consolidation des niveaux d’assortiment inf. Ex: les différentes SCA de Leclerc sont consolidées sur un Leclerc national. Permet de travailler au niveau de détails mais affiche dans les synthèses uniquement le niveau consolidé.</inlineHelpText>
    <label>Layer Nego Conso</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Set_Assortment_Budget_BU_Source__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Set_Assortment_Budget_BU_Source__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set filter for Assortment (Assortment_BU) BU Source for Budget record type</description>
    <label>Set Assortment Budget BU Source</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Set_Assortment_Budget_BU_Target__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Set_Assortment_Budget_BU_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set filter for Assortment (Assortment_BU) BU Target for Budget record type</description>
    <label>Set Assortment Budget BU Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Temporary closed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_HE__c/Negoptim__Orga_HE__c.object-meta.xml
<CustomObject>
    <description>Hierarchy of products (segmentation) needed for assortment management</description>
    <label>Hierarchy Element</label>
    <nameField>
        <label>Hierarchy Element</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarchy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Orga_HE__c/fields/Negoptim__Set_Product_link_level__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Set_Product_link_level__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use to filter Org_he lookup in Products object</description>
    <label>Set Product link level</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_HE__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <description>Give the current status of the element</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Negoptim__Brand__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Negoptim__Brand__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Negoptim__Brand_Parent__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Brand_Parent__c</fullName>
    <formula>Negoptim__Brand__r.Negoptim__Brand_Parent__r.Name</formula>
    <label>Brand Parent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Negoptim__Category__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Niveau 4 Catégorie</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Negoptim__Orga_HE__c.Negoptim__Set_Product_link_level__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_HE__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/classes/AssortmentManagementPanelCtrlTestExt.cls
@IsTest
public class AssortmentManagementPanelCtrlTestExt {
    
    private static final Map<String, Id> assortmentRTIds = Negoptim.NegoptimHelper.getObjectRecordTypeMapIds(Negoptim__Assortment_BU__c.SObjectType);
    private static Id rootId;
    private static Negoptim__Supplier__c supplier;
    private static Negoptim__Orga_HE__c department;
    private static Negoptim__Orga_HE__c section;
    private static Negoptim__Orga_HE__c section2;
    private static Product2 product;
    private static Product2 product2;
    private static Negoptim__Orga_BU__c buSource;
    private static Negoptim__Orga_BU__c buTarget;
    private static Negoptim__Assortment_BU__c assortmentBU;
    private static Negoptim__Assortment_BU__c assortmentBUBudget;
    private static Negoptim__Orga_BU__c country;
    private static Negoptim__Assortment_Detail__c assortmentDetail;
    private	static List<Negoptim__Orga_HE__c> heList1;
	private static List<Negoptim__Orga_HE__c> heList2;
    
    static void init() {
        // Root element Id.
        rootId = Negoptim.NegoptimHelper.getRootIdByRT('Product');
        // Insert Country List.
        Negoptim__Country_List__c myCountry = TestDataFactoryExt.createCountry(true, 'FRANCE', 'FR');
        // Insert Region.
        Negoptim__Orga_BU__c region = TestDataFactoryExt.createBURegion(true, 'EU');
        // Insert Country.
        country = TestDataFactoryExt.createBUCountry(false, myCountry, region.Id);
        country.Negoptim__IsMasterBU__c = true;
        insert country;
        // Create Supplier
        supplier = TestDataFactoryExt.createSupplier(false, country, true);
        insert supplier;
        // create HEs
        department = TestDataFactoryExt.createDepartment(false, rootId);
        department.Negoptim__Set_Product_link_level__c = true;
        insert department;
        section = TestDataFactoryExt.createSection(true, department.Id);
        section2 = TestDataFactoryExt.createSection(true, department.Id);
        //create Brand 
        Negoptim__Brand__c brand = TestDataFactoryExt.createBrand(true, supplier.Id);
		Negoptim__Brand__c brand2 = TestDataFactoryExt.createBrand(false, supplier.Id);
        brand2.Negoptim__Brand_Parent__c = brand.Id;
        insert brand2;
        // create Source BU Channel
        buSource = TestDataFactoryExt.createBUChannel(false, country);
        buSource.Negoptim__IsMasterBU__c = true;
        buSource.Negoptim__Set_Assortment_Budget_BU_Source__c = true;
        buSource.Negoptim__Layer_Nego_Conso__c = true;
        // create Target BU Banner
        buTarget = TestDataFactoryExt.createBUBanner(false, country);
        buTarget.Name = 'HMSM';
        buTarget.Negoptim__Category__c = department.Id;
        buTarget.Negoptim__Set_Assortment_Budget_BU_Target__c = true;
        buTarget.Negoptim__IsMasterBU__c = true;
        buTarget.Negoptim__Layer_Nego_Conso__c = true;
        insert new List<Negoptim__Orga_BU__c>{buTarget, buSource};
        // insert assortment_BU
        assortmentBU = TestDataFactoryExt.createAssortmentBU(false, buSource, buTarget, department);
        assortmentBU.Negoptim__Status__c = 'Validated';
        assortmentBU.Negoptim__Year__c = System.today().year();
        assortmentBU.RecordTypeId = assortmentRTIds.get('Simulation');
        assortmentBU.Negoptim__Assortment_type__c = 'In';
        insert assortmentBU;
        assortmentBUBudget = TestDataFactoryExt.createAssortmentBU(false, buSource, buTarget, department);
        assortmentBUBudget.Negoptim__Year__c = System.today().year();
        assortmentBUBudget.RecordTypeId = assortmentRTIds.get('Budget');
        assortmentBUBudget.Negoptim__Assortment_type__c = 'In';
        insert assortmentBUBudget;
               
        //init Orga HEs
		heList1 = TestDataFactoryExt.createElementHierarchy(4, 1);
		heList2 = TestDataFactoryExt.createElementHierarchy(4, 1);
        // Create Product.
		List<Product2> products = new List<Product2>();
		for (Integer i = 0; i < 2; i++) {
            product = TestDataFactoryExt.createProduct(false, section.Id, supplier.Id);
            product.Negoptim__Brand__c = brand.Id;
            product.Negoptim__Category__c = department.Id;
			products.add(product);
            product2 = TestDataFactoryExt.createProduct(false, section2.Id, supplier.Id);
            product2.Negoptim__Brand__c = brand2.Id;
            product2.Negoptim__Category__c = department.Id;
			products.add(product2);
		}
		insert products;
        List<Negoptim__Assortment_Detail__c> assortmentDetailsList = new List<Negoptim__Assortment_Detail__c>();
		for (Product2 product : products) {
			assortmentDetailsList.add(TestDataFactoryExt.createAssortmentDetail(false, assortmentBUBudget.Id, product, null));
			assortmentDetailsList.add(TestDataFactoryExt.createAssortmentDetail(false, assortmentBU.Id, product, null));
		}
		insert assortmentDetailsList;
    }
    static testmethod void AssortmentManagementPanel() {
        init();
        AssortmentManagementPanelCtrlExt.FilterParameter filterParam = new AssortmentManagementPanelCtrlExt.FilterParameter('', 0, '');
        String dataSerialized = AssortmentManagementPanelCtrlExt.loadData(JSON.serialize(filterParam)); 
    }
}