force-app/main/default/objects/Negoptim__Assortment_BU__c/Negoptim__Assortment_BU__c.object-meta.xml
<CustomObject>
    <label>Assortment BU</label>
    <nameField>
        <label>Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assortment BU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Assortment_parent__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Assortment_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>DV Budget circuit - 1</inlineHelpText>
    <label>Parent Assortment</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7 AND 8 AND 9 AND 10</booleanFilter>
        <errorMessage>Assortment_parent__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Conso</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conso, Conso Target, Conso Simulation</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Nego, Target, Simulation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Like 4 Like, Nego, Target, Simulation, PR</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__BU_source__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__BU_source__c</valueField>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__BU_Target__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__BU_Target__c</valueField>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__Status__c</field>
            <operation>equals</operation>
            <value>Validated, Request for Approval</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__Orga_HE__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__Orga_HE__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Assortment_BU__c</referenceTo>
    <relationshipLabel>Assortiments BU (Parent Assortment)</relationshipLabel>
    <relationshipName>Assortment_BU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__BU_source__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_source__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>For ex.
Budget = Corporate BU country  /
Target = Managing channel  = HMSM + DRIVE, PROXI, WEB , CASH &amp; CARRY.  /  

Saisir &apos;..&apos; pour accéder à l&apos;ensemble des BU possibles pour le type de DV choisi.</inlineHelpText>
    <label>BU Source</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5) OR (6 AND 7))</booleanFilter>
        <errorMessage>BU_source__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__IsMasterBU__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Budget_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Target_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conso Target, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Nego_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Conso Target, Budget, Target</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_BU__c</referenceTo>
    <relationshipName>Assortment_BU</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__BU_Target__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_Target__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Budget = HMSM + DRIVE, PROXI, WEB, CASH &amp; CARRY.  /  
target/ Nego =Banner(ex. Carrefour HM, Carrefour SM, Intermarché.fr).  /  

Saisir &apos;..&apos; pour accéder à l&apos;ensemble des BU possibles pour le type choisi.</inlineHelpText>
    <label>BU Target</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2 AND 3) OR (4 AND 5) OR (6 AND 7))</booleanFilter>
        <errorMessage>BU_Target__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Budget_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__IsMasterBU__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conso Target, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Target_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Conso Target, Budget, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Nego_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_BU__c</referenceTo>
    <relationshipName>Assortment_BU1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Ext_id__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Ext_id__c</fullName>
    <externalId>true</externalId>
    <label>Ext id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Negoptim__Assortment_type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open (in bulding process)</fullName>
                <default>true</default>
                <label>Open (in bulding process)</label>
            </value>
            <value>
                <fullName>Request for Approval</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Signed IN</fullName>
            </value>
            <value>
                <fullName>Signed OUT</fullName>
            </value>
            <value>
                <fullName>Closed (Upgraded version)</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/Negoptim__Assortment_Detail__c.object-meta.xml
<CustomObject>
    <description>Assortment product detail by BU</description>
    <label>Assortment Detail</label>
    <nameField>
        <displayFormat>ASD-{0}</displayFormat>
        <label>Assortiment Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assortment Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Assortment_BU__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Assortment_BU__c</fullName>
    <label>Assortment BU</label>
    <referenceTo>Negoptim__Assortment_BU__c</referenceTo>
    <relationshipLabel>Assortment BU Details</relationshipLabel>
    <relationshipName>Assortment_BU_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__BU_Source__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_Source__c</fullName>
    <formula>TEXT(1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BU Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__BU_Target__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_Target__c</fullName>
    <formula>Negoptim__Assortment_BU__r.Negoptim__BU_Target__r.Name</formula>
    <label>BU Target</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Category__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Negoptim__Orga_HE__c.Negoptim__Level__c</field>
            <operation>equals</operation>
            <value>3,4</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_HE__c</referenceTo>
    <relationshipLabel>Assortment BU Details</relationshipLabel>
    <relationshipName>Assortment_BU_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Ext_id__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Ext_id__c</fullName>
    <externalId>true</externalId>
    <label>Ext_id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Last_History__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Last_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field used to register the last history entry for each validated record.</description>
    <inlineHelpText>pour tracer la dernière entrée de chaque validation</inlineHelpText>
    <label>Last History</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Negoptim__Assortment_Detail__c.Negoptim__Version__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Assortment_Detail__c</referenceTo>
    <relationshipLabel>Assortment BU Details (Last History)</relationshipLabel>
    <relationshipName>Assortment_BU_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Product__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Assortment BU Details</relationshipLabel>
    <relationshipName>Assortment_BU_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>In preparation</label>
            </value>
            <value>
                <fullName>Request for Approval</fullName>
                <color>#78C953</color>
                <label>Request for Approval</label>
            </value>
            <value>
                <fullName>Validated</fullName>
                <color>#E27001</color>
                <label>Validated</label>
            </value>
            <value>
                <fullName>Previously Validated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Version__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Version__c</fullName>
    <label>Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DuplicateAssortmentDetailBatch_Ext.cls
/**
* @author ULiT
* @description Generate assortment details for duplicated assortment bu 
* @date 7/9/2023
* */
public class DuplicateAssortmentDetailBatch_Ext implements Database.Batchable<SObject> {
    
    private Negoptim.NegoptimBatch nb;
    public final String query;
    Map<String, Id> refAssortmentDetailsMap;
    Map<String, Negoptim__Assortment_BU__c> assortmnentBUMap;
    public List<String> assortmentDetailCreateUpdateFields;
    List<Id> clonedAssortmentBUIdList;
    
    public DuplicateAssortmentDetailBatch_Ext(String startedFrom, Id recordId, List<Id> parentAssortmnentIds, Map<String, Negoptim__Assortment_BU__c> assortmnentBUMap) {
        this.nb = new Negoptim.NegoptimBatch(DuplicateAssortmentDetailBatch_Ext.class.getName(), Negoptim.NegoptimBatch.BatchType.Stateless, startedFrom);
        this.assortmnentBUMap = assortmnentBUMap;
        this.clonedAssortmentBUIdList = new List<Id>();
        // get Assortment Detail field
        Map<String, Schema.SObjectField> assortmentDetailfields = Schema.Negoptim__Assortment_Detail__c.sObjectType.getDescribe().fields.getMap();
        assortmentDetailCreateUpdateFields = new List<String>();
        for (Schema.SObjectField field : assortmentDetailfields.values()) {
            Schema.DescribeFieldResult fieldResult = field.getDescribe();
            if (fieldResult.isCreateable() || fieldResult.isUpdateable()) {
                assortmentDetailCreateUpdateFields.add(fieldResult.getName());
            }
        }
        Map<Id, List<Negoptim__Assortment_Detail__c>> parentAssortmentDetails = new Map<Id, List<Negoptim__Assortment_Detail__c>>();
        refAssortmentDetailsMap = new Map<String, Id>();
        if (parentAssortmnentIds != null && !parentAssortmnentIds.isEmpty()){
            String queryParentAssortDetails = 'SELECT Id, Negoptim__Assortment_BU__r.Negoptim__BU_source__c, Negoptim__Assortment_BU__r.Negoptim__BU_Target__c, Negoptim__Assortment_BU__r.RecordTypeId, ' + String.join(assortmentDetailCreateUpdateFields, ', ') ;
            queryParentAssortDetails += ' FROM Negoptim__Assortment_Detail__c';
            queryParentAssortDetails += ' WHERE Negoptim__Version__c = NULL AND Negoptim__Status__c = \'Validated\'';
            queryParentAssortDetails += ' AND Negoptim__Assortment_BU__c IN (\'' + String.join(parentAssortmnentIds, '\', \'') +'\')';  
            List<Negoptim__Assortment_Detail__c> parentsAssortmentDList = Database.query(queryParentAssortDetails);
            for (Negoptim__Assortment_Detail__c ad : parentsAssortmentDList) {
                if (!parentAssortmentDetails.containsKey(ad.Negoptim__Assortment_BU__c)) {
                    parentAssortmentDetails.put(ad.Negoptim__Assortment_BU__c, new List<Negoptim__Assortment_Detail__c>());
                }
                parentAssortmentDetails.get(ad.Negoptim__Assortment_BU__c).add(ad);
            }
            for (Negoptim__Assortment_BU__c assortmentBU : assortmnentBUMap.values()) {
                if (parentAssortmentDetails.containsKey(assortmentBu.Negoptim__Assortment_parent__c)) {
                    for (Negoptim__Assortment_Detail__c ad : parentAssortmentDetails.get(assortmentBU.Negoptim__Assortment_parent__c)) {
                        String refKey = String.valueOf(ad.Negoptim__Product__c) + ad.Negoptim__Assortment_BU__r.Negoptim__BU_source__c + ad.Negoptim__Assortment_BU__r.Negoptim__BU_Target__c + ad.Negoptim__Assortment_BU__r.RecordTypeId;  
                        refAssortmentDetailsMap.put(refKey, ad.Id);
                    }
                } 
            } 
        }
        
        // get current Assortment Details
        String queryCurrentAssortmentDetails = 'SELECT Id, Negoptim__Assortment_BU__r.Negoptim__BU_source__c, Negoptim__Assortment_BU__r.Negoptim__BU_Target__c, Negoptim__Assortment_BU__r.RecordTypeId, ' + String.join(assortmentDetailCreateUpdateFields, ', ') ;
        queryCurrentAssortmentDetails += ' FROM Negoptim__Assortment_Detail__c';
        queryCurrentAssortmentDetails += ' WHERE Negoptim__Assortment_BU__c = \'' + recordId + '\'';
        this.query = queryCurrentAssortmentDetails;
        
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Negoptim__Assortment_Detail__c> scope) {
        List<Negoptim__Assortment_Detail__c> assortmentDetailsToInsert = new List<Negoptim__Assortment_Detail__c>();
        for(Negoptim__Assortment_BU__c assortmentBU : assortmnentBUMap.values()) {
            for (Negoptim__Assortment_Detail__c item : scope) {
                // check create permission before creating a new record
                if (Negoptim.NegoptimHelper.checkCreatibility(Negoptim__Assortment_Detail__c.SObjectType, assortmentDetailCreateUpdateFields)) {
                    Negoptim__Assortment_Detail__c newAssortmentDetail;
                    String refKey = String.valueOf(item.Negoptim__Product__c)  + assortmentBU.Negoptim__BU_source__c + assortmentBU.Negoptim__BU_Target__c + assortmentBU.RecordTypeId;
                    Id refDetail = refAssortmentDetailsMap.containsKey(refKey) ? refAssortmentDetailsMap.get(refKey) : null;
                    newAssortmentDetail = item.clone(false, true, true, false);
                    newAssortmentDetail.Negoptim__Category__c = null;
                    newAssortmentDetail.Negoptim__Assortment_BU__c = assortmentBU.Id;
                    newAssortmentDetail.Negoptim__Last_History__c = null;
                    newAssortmentDetail.Negoptim__Ext_id__c = null;
                    newAssortmentDetail.Negoptim__Ref_Client_Assortment__c = refDetail;
                    newAssortmentDetail.Negoptim__Status__c = 'In preparation';
                    assortmentDetailsToInsert.add(newAssortmentDetail);
                }
            }
            clonedAssortmentBUIdList.add(assortmentBU.Id);
        }
        if (!assortmentDetailsToInsert.isEmpty()) {
            if (Negoptim.NegoptimHelper.checkCreatibility(Negoptim__Assortment_Detail__c.SObjectType, assortmentDetailCreateUpdateFields)) {
                Database.SaveResult[] results = Database.insert(assortmentDetailsToInsert, false);
                String errorMessages = '';
                for (Integer i = 0; i < results.size(); i++) {
                    Database.SaveResult result = results.get(i);
                    Negoptim__Assortment_Detail__c record = assortmentDetailsToInsert.get(i);
                    if (!result.isSuccess()) {
                        String errorMessage = String.valueOf(record);
                        Database.Error[] errors = result.getErrors();
                        for (Database.Error err : errors) {
                            errorMessages += (err.getFields() + ':' +err.getStatusCode() + ' - ' + err.getMessage());
                            System.debug(err.getFields() + ':' +err.getStatusCode() + ' - ' + err.getMessage() + '\n');
                        }
                    }
                }
            }
        }
        nb.saveLog(bc);
    }
    
    public void finish(Database.BatchableContext bc) {
        Negoptim.NegoptimBatch.executeBatch(new Negoptim.RefreshAssortmentClusterBatch(DuplicateAssortmentDetailBatch_Ext.class.getName(), clonedAssortmentBUIdList, null, null, null), 200);
        String customSubject = DuplicateAssortmentDetailBatch_Ext.class.getName() + ' : ' + [SELECT Status, NumberOfErrors, TotalJobItems, JobItemsProcessed,
                                                                                             CompletedDate, MethodName,	CreatedBy.name, CreatedDate, ExtendedStatus
                                                                                             FROM AsyncApexJob WHERE Id = :bc.getJobId()]?.Status;
        nb.sendEmail(bc, null, customSubject);
    }

}