force-app/main/default/objects/Negoptim__Assortment_BU__c/Negoptim__Assortment_BU__c.object-meta.xml
<CustomObject>
    <label>Assortment BU</label>
    <nameField>
        <label>Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assortment BU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Ass_BDate__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Ass_BDate__c</fullName>
    <label>Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Ass_EDate__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Ass_EDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Assortment_parent__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Assortment_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>DV Budget circuit - 1</inlineHelpText>
    <label>Parent Assortment</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7 AND 8 AND 9 AND 10</booleanFilter>
        <errorMessage>Assortment_parent__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Conso</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conso, Conso Target, Conso Simulation</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Nego, Target, Simulation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Like 4 Like, Nego, Target, Simulation, PR</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__BU_source__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__BU_source__c</valueField>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__BU_Target__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__BU_Target__c</valueField>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__Status__c</field>
            <operation>equals</operation>
            <value>Validated, Request for Approval</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__Orga_HE__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__Orga_HE__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Assortment_BU__c</referenceTo>
    <relationshipLabel>Assortiments BU (Parent Assortment)</relationshipLabel>
    <relationshipName>Assortment_BU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Orga_HE__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Orga_HE__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product hierarchy</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Orga_HE__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_HE__c.Negoptim__Set_Assortment_Cluster_level__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_HE__c</referenceTo>
    <relationshipName>Assortment_BU</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Negoptim__Assortment_type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open (in bulding process)</fullName>
                <default>true</default>
                <label>Open (in bulding process)</label>
            </value>
            <value>
                <fullName>Request for Approval</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Signed IN</fullName>
            </value>
            <value>
                <fullName>Signed OUT</fullName>
            </value>
            <value>
                <fullName>Closed (Upgraded version)</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Year__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Year__c</fullName>
    <description>Campaign year</description>
    <inlineHelpText>Campaign year</inlineHelpText>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/Negoptim__Assortment_Detail__c.object-meta.xml
<CustomObject>
    <description>Assortment product detail by BU</description>
    <label>Assortment Detail</label>
    <nameField>
        <displayFormat>ASD-{0}</displayFormat>
        <label>Assortiment Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assortment Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Assortment_BU__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Assortment_BU__c</fullName>
    <label>Assortment BU</label>
    <referenceTo>Negoptim__Assortment_BU__c</referenceTo>
    <relationshipLabel>Assortment BU Details</relationshipLabel>
    <relationshipName>Assortment_BU_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>In preparation</label>
            </value>
            <value>
                <fullName>Request for Approval</fullName>
                <color>#78C953</color>
                <label>Request for Approval</label>
            </value>
            <value>
                <fullName>Validated</fullName>
                <color>#E27001</color>
                <label>Validated</label>
            </value>
            <value>
                <fullName>Previously Validated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Year__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Year__c</fullName>
    <formula>Negoptim__Assortment_BU__r.Negoptim__Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/Negoptim__Orga_BU__c.object-meta.xml
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>BU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__IsMasterBU__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__IsMasterBU__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to distinguished if the record is the master Org BU.</description>
    <inlineHelpText>Est-ce une BU (Enseigne, circuit...) sélectionnable pour l&apos;assortiment.</inlineHelpText>
    <label>Is Master BU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Temporary closed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_HE__c/Negoptim__Orga_HE__c.object-meta.xml
<CustomObject>
    <description>Hierarchy of products (segmentation) needed for assortment management</description>
    <label>Hierarchy Element</label>
    <nameField>
        <label>Hierarchy Element</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarchy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Orga_HE__c/fields/Negoptim__Set_Product_link_level__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Set_Product_link_level__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use to filter Org_he lookup in Products object</description>
    <label>Set Product link level</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_HE__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <description>Give the current status of the element</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <inlineHelpText>Etape du cycle de vie du produit</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initialization</fullName>
            </value>
            <value>
                <fullName>In process of creation</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In preparation</fullName>
            </value>
            <value>
                <fullName>Pre opening</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>On sale</fullName>
            </value>
            <value>
                <fullName>In process of deletion</fullName>
            </value>
            <value>
                <fullName>EOL</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/classes/DuplicateAssortmentBUInvocable_Ext_Test.cls
/**
* @author ULiT
* @description unit test for  Duplicate assortment bu from another assortment bu 
* @date 7/9/2023
* */
@isTest
private class DuplicateAssortmentBUInvocable_Ext_Test {
    
    private static Integer count = 20;
    private static Negoptim__Assortment_BU__c assortmentBU;
    private static Negoptim__Assortment_BU__c parentAssortmentBU;
    private static Negoptim__Orga_BU__c country;
    private static List<Product2> products;
    private static Negoptim__Orga_HE__c department ;
    private static Negoptim__Orga_HE__c section;
    private static Negoptim__Orga_BU__c buSource;
    private static Negoptim__Orga_BU__c buTarget;
    
    static void init () {
        try {
            SelectedBU bu = new SelectedBU();
            // Root element Id.
            Id rootId = Negoptim.NegoptimHelper.getRootIdByRT('Product');
            // Insert Country List.
            Negoptim__Country_List__c myCountry = TestDataFactoryExt.createCountry(true, 'FRANCE', 'FR');
            // Insert Region.
            Negoptim__Orga_BU__c region = TestDataFactoryExt.createBURegion(true, 'EU');
            // Insert Country.
            country = TestDataFactoryExt.createBUCountry(true, myCountry, region.Id);
            // Assortment BU Source
            buSource = TestDataFactoryExt.createBUBanner(false, country);
            buSource.Negoptim__isMasterBU__c = true;
            // Assortment BU Target
            buTarget = TestDataFactoryExt.createBUBanner(false, country);
            insert new List<Negoptim__Orga_BU__c> {BUSource, BUTarget};
                // create HEs
            department = TestDataFactoryExt.createDepartment(false, rootId);
            department.Negoptim__Set_Product_link_level__c = true;
            insert department;
            assortmentBU = TestDataFactoryExt.createAssortmentBU(false, buSource, buTarget, department);
            assortmentBU.Negoptim__Status__c = 'Validated';
            insert assortmentBU;
            section = TestDataFactoryExt.createSection(true, department.Id);
            // Create Assortment Details manually to cover as many cases as possible
            products = new List<Product2>();
            for(Integer i = 0; i < count; i++) {
                Product2 product = TestDataFactoryExt.createProduct(false, section.Id, null);
                products.add(product);
            }
            insert products;
            List<Negoptim__Assortment_Detail__c> assortmentDetails = new List<Negoptim__Assortment_Detail__c>();
            for(Integer i = 0; i < count; i++) {
                Negoptim__Assortment_Detail__c assortmentDetail = TestDataFactoryExt.createAssortmentDetail(false, assortmentBU.Id, products[i], null);
                assortmentDetails.add(assortmentDetail);
            }
            insert assortmentDetails;
        } catch (Exception ex) {
            System.debug(ex.getMessage() ); 
            System.debug(ex.getStackTraceString());
        }
    }
    static testmethod void cloneAssortmentBUWithSelectedBUs() {
        init();
        parentAssortmentBU = TestDataFactoryExt.createAssortmentBU(false, buSource, buTarget, department);
        Integer lastYear = System.Today().year() - 1;
        parentAssortmentBU.Negoptim__Year__c = lastYear;
        parentAssortmentBU.Negoptim__Ass_BDate__c = Date.newInstance(lastYear, 1, 1);
        parentAssortmentBU.Negoptim__Ass_EDate__c = Date.newInstance(lastYear, 12, 31);
        parentAssortmentBU.Negoptim__Status__c = 'Validated';
        insert parentAssortmentBU;
        List<Negoptim__Assortment_Detail__c> parentAssortmentDetails = new List<Negoptim__Assortment_Detail__c>();
        for(Integer i = 0; i < count; i++) {
            Negoptim__Assortment_Detail__c assortmentDetail = TestDataFactoryExt.createAssortmentDetail(false, parentAssortmentBU.Id, products[i], null);
            assortmentDetail.Negoptim__Status__c = 'Validated';
            parentAssortmentDetails.add(assortmentDetail);
        }
        insert parentAssortmentDetails;
        assortmentBU.Negoptim__Assortment_parent__c = parentAssortmentBU.Id;
        update assortmentBU;
        Test.startTest();
        DuplicateAssortmentBUInvocable_Ext.AssortmentsWrapper assortmentToBecreated = new DuplicateAssortmentBUInvocable_Ext.AssortmentsWrapper(String.valueOf(assortmentBU.Id), 
                                                                                                                                                new List<SelectedBU> {new SelectedBU(String.valueOf(buSource.Id), 
                                                                                                                                                                                     String.valueOf(buTarget.Id))},
                                                                                                                                                false);
        List<DuplicateAssortmentBUInvocable_Ext.duplicatedAssortment> dupAssortBU = DuplicateAssortmentBUInvocable_Ext.duplicateAssortmentBU(new List<DuplicateAssortmentBUInvocable_Ext.AssortmentsWrapper> {assortmentToBecreated});
        String dupAssortmentBU = dupAssortBU[0].duplicatedRecordId;
        
        Negoptim__Assortment_BU__c duplicatedAssortment = [SELECT Id, Negoptim__Assortment_parent__c, Negoptim__Year__c, Negoptim__BU_source__c, Negoptim__BU_Target__c, RecordTypeId, 
                                                           Negoptim__Assortment_parent__r.Negoptim__BU_source__c, Negoptim__Assortment_parent__r.Negoptim__BU_Target__c, Negoptim__Assortment_parent__r.RecordTypeId
                                                           FROM Negoptim__Assortment_BU__c WHERE Id = :dupAssortmentBU];
        Map<String, Negoptim__Assortment_BU__c> assortmnentBUMap = new Map<String, Negoptim__Assortment_BU__c>();
        assortmnentBUMap.put(duplicatedAssortment.Negoptim__Assortment_parent__r.RecordTypeId + '' +  duplicatedAssortment.Negoptim__Assortment_parent__r.Negoptim__BU_source__c + '' + duplicatedAssortment.Negoptim__Assortment_parent__r.Negoptim__BU_Target__c, duplicatedAssortment);
        Negoptim.NegoptimBatch.executeBatch(new DuplicateAssortmentDetailBatch_Ext(DuplicateAssortmentBUInvocable_Ext_Test.class.getName(), assortmentBU.Id, new List<Id>{parentAssortmentBU.Id}, assortmnentBUMap), 20);
        Test.stopTest(); 
        System.assertEquals(duplicatedAssortment.Negoptim__BU_source__c, buSource.Id);
        System.assertEquals(duplicatedAssortment.Negoptim__BU_Target__c, buTarget.Id);
        System.assertEquals(duplicatedAssortment.Negoptim__Assortment_parent__c, parentAssortmentBU.Id);
        List<Negoptim__Assortment_Detail__c> duplicatedAssortmentDetail = [SELECT Id
                                                                           FROM Negoptim__Assortment_Detail__c 
                                                                           WHERE Negoptim__Assortment_BU__c = :duplicatedAssortment.Id];
        
        System.assertEquals(count, duplicatedAssortmentDetail.size());
    }
    static testmethod void generateRegionalAssortment() {
        init();
        // Assortment BU Source
        Negoptim__Orga_BU__c buSource = TestDataFactoryExt.createBUBanner(false, country);
        buSource.Negoptim__isMasterBU__c = true;
        // Assortment BU Target
        Negoptim__Orga_BU__c buTarget = TestDataFactoryExt.createBUBanner(false, country);
        insert new List<Negoptim__Orga_BU__c> {buSource, buTarget};
        parentAssortmentBU = TestDataFactoryExt.createAssortmentBU(false, buSource, buTarget, department);
        Integer lastYear = System.Today().year() - 1;
        parentAssortmentBU.Negoptim__Year__c = lastYear;
        parentAssortmentBU.Negoptim__Ass_BDate__c = Date.newInstance(lastYear, 1, 1);
        parentAssortmentBU.Negoptim__Ass_EDate__c = Date.newInstance(lastYear, 12, 31);
        parentAssortmentBU.Negoptim__Status__c = 'Validated';
        insert parentAssortmentBU;
        List<Negoptim__Assortment_Detail__c> parentAssortmentDetails = new List<Negoptim__Assortment_Detail__c>();
        for(Integer i = 0; i < count; i++) {
            Negoptim__Assortment_Detail__c assortmentDetail = TestDataFactoryExt.createAssortmentDetail(false, parentAssortmentBU.Id, products[i], null);
            assortmentDetail.Negoptim__Status__c = 'Validated';
            parentAssortmentDetails.add(assortmentDetail);
        }
        insert parentAssortmentDetails;
        Test.startTest();
        DuplicateAssortmentBUInvocable_Ext.AssortmentsWrapper assortmentToBecreated = new DuplicateAssortmentBUInvocable_Ext.AssortmentsWrapper(String.valueOf(assortmentBU.Id), 
                                                                                                                                                new List<SelectedBU> {new SelectedBU(String.valueOf(buSource.Id), 
                                                                                                                                                                                     String.valueOf(buTarget.Id))},
                                                                                                                                                true);
        DuplicateAssortmentBUInvocable_Ext.duplicateAssortmentBU(new List<DuplicateAssortmentBUInvocable_Ext.AssortmentsWrapper> {assortmentToBecreated});
        //Negoptim.NegoptimBatch.executeBatch(new DuplicateAssortmentDetailBatch_Ext(DuplicateAssortmentBUInvocable_Ext.class.getName(), assortmentBU.Id, new List<id>{'parentAssortmentBU'}, new Map<String, Negoptim__Assortment_BU__c>{assortmentBU.RecordTypeId + assortmentBU.selectedBUSource + assortmentBU.selectedBUTarget}), 20);
        Test.stopTest();
    }
}