force-app/main/default/objects/Negoptim__Assortment_BU__c/Negoptim__Assortment_BU__c.object-meta.xml
<CustomObject>
    <label>Assortment BU</label>
    <nameField>
        <label>Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assortment BU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Assortment_parent__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Assortment_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>DV Budget circuit - 1</inlineHelpText>
    <label>Parent Assortment</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7 AND 8 AND 9 AND 10</booleanFilter>
        <errorMessage>Assortment_parent__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Conso</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conso, Conso Target, Conso Simulation</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Nego, Target, Simulation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Like 4 Like, Nego, Target, Simulation, PR</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__BU_source__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__BU_source__c</valueField>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__BU_Target__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__BU_Target__c</valueField>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__Status__c</field>
            <operation>equals</operation>
            <value>Validated, Request for Approval</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__Orga_HE__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__Orga_HE__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Assortment_BU__c</referenceTo>
    <relationshipLabel>Assortiments BU (Parent Assortment)</relationshipLabel>
    <relationshipName>Assortment_BU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Assortment_Parent_Objective__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Assortment_Parent_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Assortment Objective</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2 AND 3 AND 4 AND 5) OR (6 AND 7)) AND 8</booleanFilter>
        <errorMessage>Assortment_Parent_Objective__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Target, Simulation</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__Status__c</field>
            <operation>equals</operation>
            <value>Validated</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__BU_Target__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__BU_Target__c</valueField>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__BU_source__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__BU_source__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Nego</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Target, Simulation, PR</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__Orga_HE__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__Orga_HE__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Assortment_BU__c</referenceTo>
    <relationshipName>Assortment_BU_Objective</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__BU_source__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_source__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>For ex.
Budget = Corporate BU country  /
Target = Managing channel  = HMSM + DRIVE, PROXI, WEB , CASH &amp; CARRY.  /  

Saisir &apos;..&apos; pour accéder à l&apos;ensemble des BU possibles pour le type de DV choisi.</inlineHelpText>
    <label>BU Source</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5) OR (6 AND 7))</booleanFilter>
        <errorMessage>BU_source__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__IsMasterBU__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Budget_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Target_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conso Target, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Nego_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Conso Target, Budget, Target</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_BU__c</referenceTo>
    <relationshipName>Assortment_BU</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__BU_Target__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_Target__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Budget = HMSM + DRIVE, PROXI, WEB, CASH &amp; CARRY.  /  
target/ Nego =Banner(ex. Carrefour HM, Carrefour SM, Intermarché.fr).  /  

Saisir &apos;..&apos; pour accéder à l&apos;ensemble des BU possibles pour le type choisi.</inlineHelpText>
    <label>BU Target</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2 AND 3) OR (4 AND 5) OR (6 AND 7))</booleanFilter>
        <errorMessage>BU_Target__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Budget_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__IsMasterBU__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conso Target, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Target_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Conso Target, Budget, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Nego_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_BU__c</referenceTo>
    <relationshipName>Assortment_BU1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Negoptim__Assortment_type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open (in bulding process)</fullName>
                <default>true</default>
                <label>Open (in bulding process)</label>
            </value>
            <value>
                <fullName>Request for Approval</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Signed IN</fullName>
            </value>
            <value>
                <fullName>Signed OUT</fullName>
            </value>
            <value>
                <fullName>Closed (Upgraded version)</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Year__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Year__c</fullName>
    <description>Campaign year</description>
    <inlineHelpText>Campaign year</inlineHelpText>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/SPKERCADELACLevel__c.field-meta.xml
<CustomField>
    <fullName>SPKERCADELACLevel__c</fullName>
    <label>SPKERCADELAC Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>Regional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/Negoptim__Assortment_Detail__c.object-meta.xml
<CustomObject>
    <description>Assortment product detail by BU</description>
    <label>Assortment Detail</label>
    <nameField>
        <displayFormat>ASD-{0}</displayFormat>
        <label>Assortiment Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assortment Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Assortment_BU__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Assortment_BU__c</fullName>
    <label>Assortment BU</label>
    <referenceTo>Negoptim__Assortment_BU__c</referenceTo>
    <relationshipLabel>Assortment BU Details</relationshipLabel>
    <relationshipName>Assortment_BU_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__BU_Source__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_Source__c</fullName>
    <formula>TEXT(1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BU Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__BU_Target__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_Target__c</fullName>
    <formula>Negoptim__Assortment_BU__r.Negoptim__BU_Target__r.Name</formula>
    <label>BU Target</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>In preparation</label>
            </value>
            <value>
                <fullName>Request for Approval</fullName>
                <color>#78C953</color>
                <label>Request for Approval</label>
            </value>
            <value>
                <fullName>Validated</fullName>
                <color>#E27001</color>
                <label>Validated</label>
            </value>
            <value>
                <fullName>Previously Validated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DuplicateAssortmentBUInvocable_Ext.cls
/**
* @author ULiT
* @description Duplicate assortment bu from another assortment bu 
* @date 7/9/2023
* */
public class DuplicateAssortmentBUInvocable_Ext {
    
    @InvocableMethod(label='Duplicate Assortment BU' description='Duplicate Assortment BU from another Assortment BU')
    public static List<duplicatedAssortment> duplicateAssortmentBU(List<AssortmentsWrapper> assortments) {
        AssortmentsWrapper assortment = assortments[0];
        String recordId = assortment.recordId;
        List<Id> clonedAssortmentBUIdList = new List<Id>();
        
        // get Assortment_BU__c fields        
        Map<String, Schema.SObjectField> assortmentBufields = Schema.Negoptim__Assortment_BU__c.sObjectType.getDescribe().fields.getMap();
        List<String> assortmentBUCreateUpdateFields = new List<String>();
        for (Schema.SObjectField field : assortmentBufields.values()) {
            Schema.DescribeFieldResult fieldResult = field.getDescribe();
            if (fieldResult.isCreateable() || fieldResult.isUpdateable()) {
                assortmentBUCreateUpdateFields.add(fieldResult.getName());
            }
        }
        
        // get current Assortment BU
        String queryAssortment = 'SELECT Id, Negoptim__Assortment_Parent_Objective__r.RecordType.DeveloperName, ' + String.join(assortmentBUCreateUpdateFields, ', ') ; 
        queryAssortment += ' FROM Negoptim__Assortment_BU__c';
        queryAssortment += ' WHERE Id = \'' + recordId + '\'';
        Negoptim__Assortment_BU__c currentAssortmentBU = Database.query(queryAssortment);
        
        Map<String, Negoptim__Assortment_BU__c> assortmnentBUMap = new Map<String, Negoptim__Assortment_BU__c>();
        Set<String> buSourceId = new Set<String>();
        Set<String> buTargetId = new Set<String>();
        
        // Generate Assortment BU for each selectedBUSource/selectedBUTarget
        for (SelectedBU bu : assortment.selectedBU) {
            Negoptim__Assortment_BU__c duplicatedAssortmentBU = currentAssortmentBU.clone(false, true, true, false);
            duplicatedAssortmentBU.Negoptim__BU_source__c = bu.selectedBUSource;
            duplicatedAssortmentBU.Negoptim__BU_Target__c = bu.selectedBUTarget;
            duplicatedAssortmentBU.Negoptim__Status__c = 'Open (in bulding process)';
            duplicatedAssortmentBU.Negoptim__Assortment_parent__c = null ;
            duplicatedAssortmentBU.Name = '';
            if (assortment.isGenerateRegionalAssortment) {
                duplicatedAssortmentBU.SPKERCADELACLevel__c = 'Regional';
            }
            if(currentAssortmentBU.Negoptim__Assortment_Parent_Objective__r.RecordType.DeveloperName == 'Simulation'){
                duplicatedAssortmentBU.Negoptim__Assortment_Parent_Objective__c = null;
            }
            String key = currentAssortmentBU.RecordTypeId + bu.selectedBUSource + bu.selectedBUTarget;
            assortmnentBUMap.put(key, duplicatedAssortmentBU);
            buSourceId.add(bu.selectedBUSource);
            buTargetId.add(bu.selectedBUTarget);
        } 
        List<Negoptim__Assortment_Detail__c> assortmentDetailsToInsert = new List<Negoptim__Assortment_Detail__c>();
        Map<String, Id> parentAssortmnentBuMap = new Map<String, Id>();
        List<Id> parentAssortmnentIds = new List<Id>();
        //get Parent Assortment if exists
        List<Negoptim__Assortment_BU__c> parentAssortment = [SELECT Id, Negoptim__BU_source__c, Negoptim__BU_Target__c, Negoptim__Assortment_parent__c, RecordTypeId
                                                             FROM Negoptim__Assortment_BU__c
                                                             WHERE Negoptim__BU_source__c IN :buSourceId
                                                             AND Negoptim__BU_Target__c IN :buTargetId
                                                             AND Negoptim__Status__c = 'Validated'
                                                             AND Negoptim__Year__c = :(Integer.valueOf(currentAssortmentBU.Negoptim__Year__c) - 1)
                                                             AND RecordTypeId = :currentAssortmentBU.RecordTypeId];
        if (parentAssortment != null && !parentAssortment.isEmpty()) {
            for (Negoptim__Assortment_BU__c parentAss : parentAssortment) {
                String key = String.valueOf(parentAss.RecordTypeId) + parentAss.Negoptim__BU_source__c + parentAss.Negoptim__BU_Target__c;
                parentAssortmnentBuMap.put(key, parentAss.Id);
                if (Negoptim.NegoptimHelper.checkAccessibility(Negoptim__Assortment_BU__c.SObjectType, assortmentBUCreateUpdateFields)) {
                    if (assortmnentBUMap.containsKey(key) && parentAssortmnentBuMap.size() != 0 && parentAssortmnentBuMap.containsKey(key)) {
                        Negoptim__Assortment_BU__c clonedAssortmentBU = assortmnentBUMap.get(key);
                        clonedAssortmentBU.Negoptim__Assortment_parent__c = parentAssortmnentBuMap.containsKey(key) ? parentAss.Id : null;
                        parentAssortmnentIds.add(parentAss.Id);
                        assortmnentBUMap.put(key, clonedAssortmentBU);
                        //assortmentBUToUpdate.add(assortmnentBUMap.get(key));
                    }
                }
            }
        }
        // Insert cloned Assortment BU
        if (Negoptim.NegoptimHelper.checkCreatibility(Negoptim__Assortment_BU__c.SObjectType, assortmentBUCreateUpdateFields)) {
           insert assortmnentBUMap.values();
        }
        if (!Test.isRunningTest()) {
           Negoptim.NegoptimBatch.executeBatch(new DuplicateAssortmentDetailBatch_Ext(DuplicateAssortmentBUInvocable_Ext.class.getName(), recordId, parentAssortmnentIds, assortmnentBUMap), 20);
        }
        if (assortment.isGenerateRegionalAssortment) {
            return null;  
        }
        return new List<duplicatedAssortment> { new duplicatedAssortment(String.valueOf(assortmnentBUMap.values()[0].Id))};
            }
    
    public class AssortmentsWrapper {
        @InvocableVariable(label='Assortment BU Id' description='Assortment BU Id' required=true)
        public String recordId;
        @InvocableVariable(label='List of selected Business Units' description='List of selected Business Units' required=true)
        public List<SelectedBU> selectedBU;
        @InvocableVariable(label='is Generate Regional Assortment' description='is Generate Regional Assortment' required=true)
        public Boolean isGenerateRegionalAssortment;
        public AssortmentsWrapper(){}
        public AssortmentsWrapper(String recordId, List<SelectedBU> selectedBU, Boolean isGenerateRegionalAssortment) {
            this.recordId = recordId;
            this.selectedBU = selectedBU;
            this.isGenerateRegionalAssortment = isGenerateRegionalAssortment;
        }
    }
    public class duplicatedAssortment{
        @InvocableVariable(label='record Id of duplicated assortment' description='record Id of duplicated assortment')
        public String duplicatedRecordId;
        duplicatedAssortment(String duplicatedRecordId){
            this.duplicatedRecordId = duplicatedRecordId;
        }
    }
}