force-app/main/default/objects/Negoptim__Assortment_BU__c/Negoptim__Assortment_BU__c.object-meta.xml
<CustomObject>
    <label>Assortment BU</label>
    <nameField>
        <label>Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assortment BU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Assortment_type__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Assortment_type__c</fullName>
    <label>Assortment type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__BU_source__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_source__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>For ex.
Budget = Corporate BU country  /
Target = Managing channel  = HMSM + DRIVE, PROXI, WEB , CASH &amp; CARRY.  /  

Saisir &apos;..&apos; pour accéder à l&apos;ensemble des BU possibles pour le type de DV choisi.</inlineHelpText>
    <label>BU Source</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5) OR (6 AND 7))</booleanFilter>
        <errorMessage>BU_source__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__IsMasterBU__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Budget_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Target_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conso Target, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Nego_BU_Source__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Conso Target, Budget, Target</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_BU__c</referenceTo>
    <relationshipName>Assortment_BU</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__BU_Target__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__BU_Target__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Budget = HMSM + DRIVE, PROXI, WEB, CASH &amp; CARRY.  /  
target/ Nego =Banner(ex. Carrefour HM, Carrefour SM, Intermarché.fr).  /  

Saisir &apos;..&apos; pour accéder à l&apos;ensemble des BU possibles pour le type choisi.</inlineHelpText>
    <label>BU Target</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2 AND 3) OR (4 AND 5) OR (6 AND 7))</booleanFilter>
        <errorMessage>BU_Target__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Budget_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__IsMasterBU__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conso Target, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Target_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Conso Target, Budget, Target</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Orga_BU__c.Negoptim__Set_Assortment_Nego_BU_Target__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_BU__c</referenceTo>
    <relationshipName>Assortment_BU1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Logo__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Logo__c</fullName>
    <label>Logo</label>
    <length>20000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Negoptim__Assortment_type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open (in bulding process)</fullName>
                <default>true</default>
                <label>Open (in bulding process)</label>
            </value>
            <value>
                <fullName>Request for Approval</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Signed IN</fullName>
            </value>
            <value>
                <fullName>Signed OUT</fullName>
            </value>
            <value>
                <fullName>Closed (Upgraded version)</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Year__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Year__c</fullName>
    <description>Campaign year</description>
    <inlineHelpText>Campaign year</inlineHelpText>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/SPKERC_SumNewClientNDCltBasedPtsGapNegoP__c.field-meta.xml
<CustomField>
    <fullName>SPKERC_SumNewClientNDCltBasedPtsGapNegoP__c</fullName>
    <label>Ecart DN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/SPKERC_SumNewClientQuantityYE__c.field-meta.xml
<CustomField>
    <fullName>SPKERC_SumNewClientQuantityYE__c</fullName>
    <description>It is the sum of new client quantity YE field</description>
    <label>Quantités +/-</label>
    <summarizedField>Negoptim__Assortment_Detail__c.Negoptim__New_Client_Quantity_YE__c</summarizedField>
    <summaryForeignKey>Negoptim__Assortment_Detail__c.Negoptim__Assortment_BU__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/Negoptim__Orga_BU__c.object-meta.xml
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>BU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Logo__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Logo__c</fullName>
    <formula>IMAGE(&apos;/resource/LogosBU&apos; + RecordType.DeveloperName + &apos;/LogosBU&apos; + RecordType.DeveloperName + &apos;/&apos; +  Negoptim__BU_Code__c +&apos;.png&apos;, &apos;&apos; , 45, 90)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Logo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Related_Client__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Related_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BU related to the client (CPG feature)</description>
    <label>Related Client</label>
    <referenceTo>Negoptim__Supplier__c</referenceTo>
    <relationshipLabel>Business Units</relationshipLabel>
    <relationshipName>Business_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Temporary closed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssortmentManagementPanelCtrlExt.cls
public with sharing class AssortmentManagementPanelCtrlExt {

    @AuraEnabled
    public static string loadData(String FilterParameterJSON) {
        try {
            ResultWrapper res = new ResultWrapper();
            FilterParameter filterParam = (FilterParameter) JSON.deserialize(FilterParameterJSON, FilterParameter.class);
            List<String> queriedAssortmetnfields = new List<String>{ 
                SObjectType.Negoptim__Assortment_BU__c.fields.Negoptim__Year__c.Name,  
                SObjectType.Negoptim__Assortment_BU__c.fields.Name.Name,       
                SObjectType.Negoptim__Assortment_BU__c.fields.SPKERC_SumNewClientQuantityYE__c.Name,       
                SObjectType.Negoptim__Assortment_BU__c.fields.SPKERC_SumNewClientProductNumberGap__c.Name,       
                SObjectType.Negoptim__Assortment_BU__c.fields.SPKERC_SumNewClientNDCltBasedPtsGapNegoP__c.Name,       
                SObjectType.Negoptim__Assortment_BU__c.fields.SPKERC_SumNewClientWDMarketBasedGap__c.Name,    
                Negoptim.NegoptimHelper.getFieldNameAsRelation(SObjectType.Negoptim__Assortment_BU__c.fields.Negoptim__BU_source__c.Name) + '.' + SObjectType.Negoptim__Orga_BU__c.fields.Name.Name,
                Negoptim.NegoptimHelper.getFieldNameAsRelation(SObjectType.Negoptim__Assortment_BU__c.fields.Negoptim__BU_Target__c.Name) + '.' + SObjectType.Negoptim__Orga_BU__c.fields.Name.Name,
                Negoptim.NegoptimHelper.getFieldNameAsRelation(SObjectType.Negoptim__Assortment_BU__c.fields.Negoptim__BU_Target__c.Name) + '.' + SObjectType.Negoptim__Orga_BU__c.fields.Negoptim__Logo__c.Name
            };
            String query = 'SELECT Id, RecordType.DeveloperName, ToLabel(Negoptim__Status__c), ' + String.join(queriedAssortmetnfields, ', ');
            query += ' FROM Negoptim__Assortment_BU__c ';
            query += ' WHERE Negoptim__Year__c = ' + filterParam.yearParam;
            if(!String.isBlank(filterParam.typeAssParam)){
                query += ' AND Negoptim__Assortment_type__c = \'' + filterParam.typeAssParam + '\'';
            }
            if(!String.isBlank(filterParam.clientParam)){
                query += ' AND Negoptim__BU_Target__r.Negoptim__Related_Client__c = \'' + filterParam.clientParam + '\'';
            }
            System.debug('query: ' + query);
            res.assortmentBuStringify = database.query(query);
            res.displayedFields = fillDisplayedFields();
            return JSON.serialize(res);
        } catch (Exception e) {
            System.debug('Error load assortmentPanel ::>>>'+ e.getMessage() + '--' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }
    private static List<FieldWrapper> fillDisplayedFields() {
        Map<String,Schema.SObjectField> assBuFields = Schema.Negoptim__Assortment_BU__c.SObjectType.getDescribe().fields.getMap();
        List<FieldWrapper> displayedFields = new List<FieldWrapper>();
        List<String> fields = new List<String>{
            SObjectType.Negoptim__Assortment_BU__c.fields.Negoptim__Year__c.Name,  
            SObjectType.Negoptim__Assortment_BU__c.fields.Negoptim__BU_source__c.Name,
            SObjectType.Negoptim__Assortment_BU__c.fields.Negoptim__BU_Target__c.Name,
            SObjectType.Negoptim__Assortment_BU__c.fields.Name.Name,
            SObjectType.Negoptim__Assortment_BU__c.fields.Negoptim__Status__c.Name,       
            SObjectType.Negoptim__Assortment_BU__c.fields.SPKERC_SumNewClientQuantityYE__c.Name,       
            SObjectType.Negoptim__Assortment_BU__c.fields.SPKERC_SumNewClientProductNumberGap__c.Name,       
            SObjectType.Negoptim__Assortment_BU__c.fields.SPKERC_SumNewClientNDCltBasedPtsGapNegoP__c.Name,       
            SObjectType.Negoptim__Assortment_BU__c.fields.SPKERC_SumNewClientWDMarketBasedGap__c.Name       
            // SObjectType.Negoptim__Assortment_BU__c.fields.Negoptim__Assortment_type__c.Name
        };
        
        for (String fieldName : fields) {
            Schema.DescribeFieldResult dfr = assBuFields.get(fieldName).getDescribe();
            FieldWrapper field = new FieldWrapper(fieldName, dfr.getLabel(), dfr.getType().Name());
            
            displayedFields.add(field);
        }
        return displayedFields;
    }
    
    public class ResultWrapper {
        public List<FieldWrapper> displayedFields {get; set;}
        public List<Negoptim__Assortment_BU__c> assortmentBuStringify {get; set;}
        
        public ResultWrapper() {}
    }

    /* Wrapper class for FieldWrapper */
    public class FieldWrapper {
        public String fieldApiName;
        public String fieldLabel;
        public String fieldType;
        public FieldWrapper(String fieldApiName, String fieldLabel, String fieldType) {
            this.fieldApiName = fieldApiName;
            this.fieldLabel = fieldLabel;
            this.fieldType = fieldType;
        }
    }
    
    public class FilterParameter {
        public String typeAssParam;
        public Integer yearParam;
        public String clientParam;
        public FilterParameter(String typeAssParam, Integer yearParam, String clientParam) {
            this.typeAssParam = typeAssParam;
            this.yearParam = yearParam;
            this.clientParam = clientParam;
        }
    }
}