force-app/main/default/objects/Negoptim__Assortment_BU__c/Negoptim__Assortment_BU__c.object-meta.xml
<CustomObject>
    <label>Assortment BU</label>
    <nameField>
        <label>Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assortment BU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Orga_HE__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Orga_HE__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product hierarchy</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Orga_HE__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Orga_HE__c.Negoptim__Set_Assortment_Cluster_level__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_HE__c</referenceTo>
    <relationshipName>Assortment_BU</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/SPKERCADELACVersionforcompilation__c.field-meta.xml
<CustomField>
    <fullName>SPKERCADELACVersionforcompilation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SPKERCADELAC Version Ok for compilation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/Negoptim__Orga_BU__c.object-meta.xml
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>BU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Format_Origin__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Format_Origin__c</fullName>
    <description>Define the Format for the banner, store, store list.</description>
    <inlineHelpText>Format (ou circuit) de l&apos;enseigne</inlineHelpText>
    <label>Format Origin</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Negoptim__BU_Store_Format</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__IsMasterBU__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__IsMasterBU__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to distinguished if the record is the master Org BU.</description>
    <inlineHelpText>Est-ce une BU (Enseigne, circuit...) sélectionnable pour l&apos;assortiment.</inlineHelpText>
    <label>Is Master BU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_BU__c/fields/Negoptim__Mission__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Mission__c</fullName>
    <label>Mission</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
                <default>true</default>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Merchandizing</fullName>
            </value>
            <value>
                <fullName>Buying</fullName>
            </value>
            <value>
                <fullName>Sales development</fullName>
            </value>
            <value>
                <fullName>Supply</fullName>
            </value>
            <value>
                <fullName>Floor animation</fullName>
            </value>
            <value>
                <fullName>Business Control</fullName>
            </value>
            <value>
                <fullName>Quality control</fullName>
            </value>
            <value>
                <fullName>Panelist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Orga_HE__c/Negoptim__Orga_HE__c.object-meta.xml
<CustomObject>
    <description>Hierarchy of products (segmentation) needed for assortment management</description>
    <label>Hierarchy Element</label>
    <nameField>
        <label>Hierarchy Element</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarchy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Negoptim__BU_Store_Format.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hypermarket</fullName>
    </customValue>
    <customValue>
        <fullName>Supermarket</fullName>
    </customValue>
    <customValue>
        <fullName>Citymarket</fullName>
    </customValue>
    <customValue>
        <fullName>Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
        <label>Ecommerce</label>
    </customValue>
    <customValue>
        <fullName>Cash&amp;Carry</fullName>
    </customValue>
    <customValue>
        <fullName>Warehouse</fullName>
    </customValue>
    <customValue>
        <fullName>Harddiscount</fullName>
    </customValue>
    <customValue>
        <fullName>HMSM</fullName>
    </customValue>
    <customValue>
        <fullName>SMDP</fullName>
        <isActive>false</isActive>
        <label>SMDP</label>
    </customValue>
    <customValue>
        <fullName>OOH</fullName>
        <isActive>false</isActive>
        <label>OOH</label>
    </customValue>
    <description>Format of the store or of the store list</description>
    <masterLabel>BU Store Format</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Trg_Assortment_BU_Handler_Ext_Test.cls
@isTest
public class Trg_Assortment_BU_Handler_Ext_Test {
	static List<Negoptim__Orga_HE__c> heList1;
	static List<Negoptim__Orga_HE__c> heList2;
	private static Negoptim__Assortment_BU__c assortment1;
	private static Negoptim__Assortment_BU__c assortment2;
	private static Negoptim__Orga_BU__c buSource;
    private static Negoptim__Orga_BU__c buTarget;
    private static Negoptim__Orga_BU__c country;

	static void init() {
		Negoptim__Orga_BU__c region = TestDataFactoryExt.CreateBURegion(true, 'region');
		Negoptim__Country_List__c countryList = TestDataFactoryExt.createCountry(true, 'France', 'FR');
		country = TestDataFactoryExt.createBUCountry(true, countryList, region.Id);
		buSource = TestDataFactoryExt.createBUChannel(false, country);
        buSource.Negoptim__Format_Origin__c = null;
		buSource.Negoptim__IsMasterBU__c = true;
		buTarget = TestDataFactoryExt.createBUBanner(false, country);
        buTarget.Negoptim__Format_Origin__c = null;
		buTarget.Negoptim__Mission__c = 'Offer';
		buTarget.Negoptim__IsMasterBU__c = false;
		insert new List<Negoptim__Orga_BU__c> {buSource, buTarget};
		//init Orga HEs
		heList1 = TestDataFactoryExt.createElementHierarchy(4, 1);
		heList2 = TestDataFactoryExt.createElementHierarchy(4, 1);
		assortment1 = TestDataFactoryExt.createAssortmentBU(false, buSource, buTarget, heList1[1]);
		assortment2 = TestDataFactoryExt.createAssortmentBU(false, buSource, buTarget, heList2[1]);
		insert new List<Negoptim__Assortment_BU__c> {assortment1, assortment2};
          List<Negoptim__Assortment_BU__c> listbu = [SELECT Name FROM Negoptim__Assortment_BU__c ];
        system.debug(JSON.serialize(listbu));
	}
	@isTest
	static void case1_after_Update() {
		init();
		assortment1.SPKERCADELACVersionforcompilation__c = true;
        update assortment1;
		Test.startTest();
		assortment2.SPKERCADELACVersionforcompilation__c = true;
        update assortment2;
		test.stopTest();
        assortment1 = [SELECT Id, SPKERCADELACVersionforcompilation__c FROM Negoptim__Assortment_BU__c WHERE Id = :assortment1.Id];
		System.assertEquals(false, assortment1.SPKERCADELACVersionforcompilation__c);
	}

}