force-app/main/default/objects/Negoptim__Assortment_BU__c/Negoptim__Assortment_BU__c.object-meta.xml
<CustomObject>
    <label>Assortment BU</label>
    <nameField>
        <label>Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assortment BU</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Assortment_Parent_Objective__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Assortment_Parent_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Assortment Objective</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2 AND 3 AND 4 AND 5) OR (6 AND 7)) AND 8</booleanFilter>
        <errorMessage>Assortment_Parent_Objective__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Target, Simulation</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__Status__c</field>
            <operation>equals</operation>
            <value>Validated</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__BU_Target__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__BU_Target__c</valueField>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__BU_source__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__BU_source__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Nego</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Target, Simulation, PR</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <filterItems>
            <field>Negoptim__Assortment_BU__c.Negoptim__Orga_HE__c</field>
            <operation>equals</operation>
            <valueField>$Source.Negoptim__Orga_HE__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Assortment_BU__c</referenceTo>
    <relationshipName>Assortment_BU_Objective</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Ext_id__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Ext_id__c</fullName>
    <externalId>true</externalId>
    <label>Ext id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_BU__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Negoptim__Assortment_type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open (in bulding process)</fullName>
                <default>true</default>
                <label>Open (in bulding process)</label>
            </value>
            <value>
                <fullName>Request for Approval</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Signed IN</fullName>
            </value>
            <value>
                <fullName>Signed OUT</fullName>
            </value>
            <value>
                <fullName>Closed (Upgraded version)</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/Negoptim__Assortment_Detail__c.object-meta.xml
<CustomObject>
    <description>Assortment product detail by BU</description>
    <label>Assortment Detail</label>
    <nameField>
        <displayFormat>ASD-{0}</displayFormat>
        <label>Assortiment Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assortment Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Assortment_BU__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Assortment_BU__c</fullName>
    <label>Assortment BU</label>
    <referenceTo>Negoptim__Assortment_BU__c</referenceTo>
    <relationshipLabel>Assortment BU Details</relationshipLabel>
    <relationshipName>Assortment_BU_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Category__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Negoptim__Orga_HE__c.Negoptim__Level__c</field>
            <operation>equals</operation>
            <value>3,4</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Orga_HE__c</referenceTo>
    <relationshipLabel>Assortment BU Details</relationshipLabel>
    <relationshipName>Assortment_BU_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Keep</fullName>
                <color>#0B6FCE</color>
                <label>Keep</label>
            </value>
            <value>
                <fullName>Delete</fullName>
                <color>#78C953</color>
                <label>Delete</label>
            </value>
            <value>
                <fullName>New</fullName>
                <color>#E27001</color>
                <label>New</label>
            </value>
            <value>
                <fullName>Increase</fullName>
                <color>#A845DC</color>
                <label>Increase</label>
            </value>
            <value>
                <fullName>Decrease</fullName>
                <color>#F3D904</color>
                <label>Decrease</label>
            </value>
            <value>
                <fullName>Substitute</fullName>
                <color>#A53711</color>
                <label>Substitute</label>
            </value>
            <value>
                <fullName>Probably deleted</fullName>
                <color>#F96FB7</color>
                <label>Probably deleted</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Cplt</fullName>
                <color>#A53711</color>
                <label>Complément</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Ext_id__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Ext_id__c</fullName>
    <externalId>true</externalId>
    <label>Ext_id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Last_History__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Last_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field used to register the last history entry for each validated record.</description>
    <inlineHelpText>pour tracer la dernière entrée de chaque validation</inlineHelpText>
    <label>Last History</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Negoptim__Assortment_Detail__c.Negoptim__Version__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Assortment_Detail__c</referenceTo>
    <relationshipLabel>Assortment BU Details (Last History)</relationshipLabel>
    <relationshipName>Assortment_BU_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Product__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Assortment BU Details</relationshipLabel>
    <relationshipName>Assortment_BU_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Ref_Client_Assortment__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Ref_Client_Assortment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ref Client Assortment</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ref_Client_Assortment__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Assortment_Detail__c.Negoptim__Assortment_BU__r.Negoptim__Assortment_type__c</field>
            <operation>equals</operation>
            <value>In, Out</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Assortment_Detail__c</referenceTo>
    <relationshipLabel>Assortment BU Details (Ref Client Assortment)</relationshipLabel>
    <relationshipName>Assortment_BU_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Ref_Corp_Assortment__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Ref_Corp_Assortment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ref Corp Assortment</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ref_Corp_Assortment__c - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Negoptim__Assortment_Detail__c.Negoptim__Assortment_BU__r.Negoptim__Assortment_type__c</field>
            <operation>equals</operation>
            <value>In</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Negoptim__Assortment_Detail__c</referenceTo>
    <relationshipLabel>Assortment BU Details</relationshipLabel>
    <relationshipName>Assortment_BU_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Status__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In preparation</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>In preparation</label>
            </value>
            <value>
                <fullName>Request for Approval</fullName>
                <color>#78C953</color>
                <label>Request for Approval</label>
            </value>
            <value>
                <fullName>Validated</fullName>
                <color>#E27001</color>
                <label>Validated</label>
            </value>
            <value>
                <fullName>Previously Validated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negoptim__Assortment_Detail__c/fields/Negoptim__Version__c.field-meta.xml
<CustomField>
    <fullName>Negoptim__Version__c</fullName>
    <label>Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CloneAssortmentDetailsInvocableExt.cls
/**
 * Called from process builder to
 * Clone assortment details from assortment parent
 * Valid for single clone
 * */
global class CloneAssortmentDetailsInvocableExt {

    @InvocableMethod(label='Clone Assortment Details From Parent Objective' description='Clone Assortment Details From Parent Objective')
    public static void cloneAssortmentDetails(List<AssortmentsWrapper> assortments) {
        Negoptim__Assortment_BU__c assortment;
        Set<Id> parentAssortmentObjSet = new Set<Id>();
        Map<Id, Negoptim__Assortment_BU__c> parentObjectiveAssortmentMap = new Map<Id, Negoptim__Assortment_BU__c>();
        List<Negoptim__Assortment_Detail__c> assortmentDetailsToInsert = new List<Negoptim__Assortment_Detail__c>();
        // check security on Assortment_Detail__c fields
        String[] assortmentDetailCreateFields = new String[] {
            SObjectType.Negoptim__Assortment_Detail__c.fields.Negoptim__Assortment_BU__c.Name,
            SObjectType.Negoptim__Assortment_Detail__c.fields.Negoptim__Product__c.Name,
            SObjectType.Negoptim__Assortment_Detail__c.fields.Negoptim__Client_Status__c.Name,
            SObjectType.Negoptim__Assortment_Detail__c.fields.Negoptim__Status__c.Name,
            SObjectType.Negoptim__Assortment_Detail__c.fields.Negoptim__Ref_Client_Assortment__c.Name,
            SObjectType.Negoptim__Assortment_Detail__c.fields.Negoptim__Last_History__c.Name,
            SObjectType.Negoptim__Assortment_Detail__c.fields.Negoptim__Ext_id__c.Name
        };
        AssortmentsWrapper itemWrapper = assortments[0];
		if (itemWrapper.cloneDetailsFromParentObjective && itemWrapper.assortment.Negoptim__Assortment_Parent_Objective__c != null && !parentAssortmentObjSet.contains(itemWrapper.assortment.Negoptim__Assortment_Parent_Objective__c)) {
            parentAssortmentObjSet.add(itemWrapper.assortment.Negoptim__Assortment_Parent_Objective__c);
            parentObjectiveAssortmentMap.put(itemWrapper.assortment.Negoptim__Assortment_Parent_Objective__c, itemWrapper.assortment);
        }
        if (!parentAssortmentObjSet.isEmpty()) {
            Map<String, Schema.SObjectField> fields = Schema.Negoptim__Assortment_Detail__c.sObjectType.getDescribe().fields.getMap();
            List<String> editableFields = new List<String>();
            for (Schema.SObjectField fieldRef : fields.values()) {
                Schema.DescribeFieldResult fieldResult = fieldRef.getDescribe();
                if (fieldResult.isCreateable() || fieldResult.isUpdateable()) {
                    editableFields.add(fieldResult.getname());
                }
            }
            // get assortment details
            String query = 'SELECT Id, ' + String.join(editableFields, ',');
            query += ' FROM Negoptim__Assortment_Detail__c';
            query += ' WHERE Negoptim__Version__c = NULL';
            query += ' AND Negoptim__Assortment_BU__c IN (\'' + String.join(new List<Id>(parentAssortmentObjSet), '\',\'') +'\')';
            String[] assortmentDetailAccessFields = new String[] {
                SObjectType.Negoptim__Assortment_Detail__c.fields.Id.Name
            };
            for (String str : editableFields) {
                if (!assortmentDetailAccessFields.contains(str)) {
                    assortmentDetailAccessFields.add(str);
                }
            }
            if (Negoptim.NegoptimHelper.checkAccessibility(Negoptim__Assortment_Detail__c.SObjectType, assortmentDetailAccessFields)) {
                List<Negoptim__Assortment_Detail__c> assortmentDetails = Database.query(query);
                for (Negoptim__Assortment_Detail__c item : assortmentDetails) {
                    assortment = parentObjectiveAssortmentMap.get(item.Negoptim__Assortment_BU__c);
                    // check create permission before creating a new record
                    if (Negoptim.NegoptimHelper.checkCreatibility(Negoptim__Assortment_Detail__c.SObjectType, assortmentDetailCreateFields)) {
                        Negoptim__Assortment_Detail__c newAssortmentDetail = item.clone(false, true, true, false);
						newAssortmentDetail.Negoptim__Category__c = null;
                        newAssortmentDetail.Negoptim__Assortment_BU__c = assortment.Id;
                        newAssortmentDetail.Negoptim__Last_History__c = null;
                        newAssortmentDetail.Negoptim__Ext_id__c = null;
                        newAssortmentDetail.Negoptim__Status__c = item.Negoptim__Client_Status__c != null && assortment.Negoptim__Status__c == 'Validated' ? 'Validated' : 'In preparation';
                        newAssortmentDetail.Negoptim__Client_Status__c = item.Negoptim__Client_Status__c;
                        newAssortmentDetail.Negoptim__Ref_Corp_Assortment__c = item.Id;
                        assortmentDetailsToInsert.add(newAssortmentDetail);
                    }
                }
            }
        }
        system.debug('assortmentDetailsToInsert >>> ' + assortmentDetailsToInsert.size());
        if (!assortmentDetailsToInsert.isEmpty()) {
            if (Negoptim.NegoptimHelper.checkCreatibility(Negoptim__Assortment_Detail__c.SObjectType, assortmentDetailCreateFields)) {
                Database.SaveResult[] results = Database.insert(assortmentDetailsToInsert, false);
                String errorMessages = '';
                for (Integer i = 0; i < results.size(); i++) {
                    Database.SaveResult result = results.get(i);
                    Negoptim__Assortment_Detail__c record = assortmentDetailsToInsert.get(i);
                    if (!result.isSuccess()) {
                        String errorMessage = String.valueOf(record);
                        Database.Error[] errors = result.getErrors();
                        for (Database.Error err : errors) {
                            errorMessages += ('\nProduct2 Id [' + record.Negoptim__Product__c + '] ' + err.getFields() + ':' +err.getStatusCode() + ' - ' + err.getMessage());
                            System.debug(err.getFields() + ':' +err.getStatusCode() + ' - ' + err.getMessage() + '\n');
                        }
                    }
                }
                if (String.isNotBlank(errorMessages)) {
                    throw new HandledException(errorMessages);
                }
            }
        }
    }
    public class AssortmentsWrapper {
        @InvocableVariable(label='Assortment' description='Assortment' required=true)
        public Negoptim__Assortment_BU__c assortment;
        @InvocableVariable(label='Copy Details From Parent Objective' description='Copy Details From Parent Objective' required=true)
        public Boolean cloneDetailsFromParentObjective;
    }
}